name: pico-fido-firmwares matrix build

on:
  workflow_dispatch:
    inputs:
      releaseTag:
        type: string
        description: Tag used at release

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

permissions:
  contents: write

jobs:
  build-and-release:
    runs-on: librekeys-nixos-x64-runner
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Matrix compile
        run: nix build .#pico-fido-firmwares

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.event.inputs.releaseTag }}
          make_latest: true

      - name: Upload files
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          nix shell nixpkgs#gh -c bash -c '
            printf "%s\0" result/share/pico-fido/* | xargs -0 -P 4 -I {} gh release upload "${{ github.event.inputs.releaseTag }}" "{}" --clobber
          '
